
# cargo-vet config file

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.atty]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bstr]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.11.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.73"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chunked_transfer]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "3.2.18"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "3.2.18"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.ctrlc]]
version = "3.2.3"
criteria = "safe-to-deploy"

[[exemptions.difflib]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.doc-comment]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.3"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.132"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.matches]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.25.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.3.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.predicates]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.predicates-core]]
version = "1.0.3"
criteria = "safe-to-run"

[[exemptions.predicates-tree]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.43"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.27"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.16.20"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.20.6"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.sct]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.85"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.termtree]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.unicase]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.ureq]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.2.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.webpki]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

